insert into image (content, image_type, title, url)
values ('에어비앤비가 엄선한 위시리스트를 만나보세요.', 'HERO', '슬기로운 자연생활', 'https://yansebnb.s3.ap-northeast-2.amazonaws.com/main/main_image.webp'),
       ('차로 10분거리', 'AROUND', '안산', 'https://yansebnb.s3.ap-northeast-2.amazonaws.com/main/around_ansan.webp'),
       ('차러 40분거리', 'AROUND', '부천', 'https://yansebnb.s3.ap-northeast-2.amazonaws.com/main/around_bucheon.webp'),
       ('차러 5시간거리', 'AROUND', '대구', 'https://yansebnb.s3.ap-northeast-2.amazonaws.com/main/around_daegu.webp'),
       ('차로 3시간거리', 'AROUND', '대전', 'https://yansebnb.s3.ap-northeast-2.amazonaws.com/main/around_daejeon.webp'),
       ('차로 4시간거리', 'AROUND', '광주', 'https://yansebnb.s3.ap-northeast-2.amazonaws.com/main/around_gwangju.webp'),
       ('차로 1시간거리', 'AROUND', '인천', 'https://yansebnb.s3.ap-northeast-2.amazonaws.com/main/around_incheon.webp'),
       ('차로 30분거리', 'AROUND', '서울', 'https://yansebnb.s3.ap-northeast-2.amazonaws.com/main/around_seoul.webp'),
       ('차로 1시간거리', 'AROUND', '수원', 'https://yansebnb.s3.ap-northeast-2.amazonaws.com/main/around_suwon.webp'),
       ('차로 1시간거리', 'AROUND', '의정부', 'https://yansebnb.s3.ap-northeast-2.amazonaws.com/main/around_uijeongbu.webp'),
       ('차로 6시간거리', 'AROUND', '울산', 'https://yansebnb.s3.ap-northeast-2.amazonaws.com/main/around_ulsan.webp'),
       ('얀네집', 'RECOMMENDATION', '얀네집', 'https://yansebnb.s3.ap-northeast-2.amazonaws.com/main/recommendation__entire.webp'),
       ('자연생활을 만끽할 수 있는 숙소', 'RECOMMENDATION', '자연생활을 만끽할 수 있는 숙소', 'https://yansebnb.s3.ap-northeast-2.amazonaws.com/main/recommendation_natural.webp'),
       ('한세네집', 'RECOMMENDATION', '한세네집', 'https://yansebnb.s3.ap-northeast-2.amazonaws.com/main/recommendation_pets.webp'),
       ('독특한공간', 'RECOMMENDATION', '독특한공간', 'https://yansebnb.s3.ap-northeast-2.amazonaws.com/main/recommendation_unique.webp');

insert into members (email, members_name, members_image)
values ('hanse@github.com', 'hanse', 'https://yansebnb.s3.ap-northeast-2.amazonaws.com/main/recommendation_unique.webp'),
       ('yan@github.com', 'yan', 'https://yansebnb.s3.ap-northeast-2.amazonaws.com/main/recommendation_unique.webp'),
       ('funny@github.com', 'funny', 'https://yansebnb.s3.ap-northeast-2.amazonaws.com/main/recommendation_unique.webp'),
       ('han@github.com', 'han', 'https://yansebnb.s3.ap-northeast-2.amazonaws.com/main/recommendation_unique.webp'),
       ('test2@github.com', 'kim', 'https://yansebnb.s3.ap-northeast-2.amazonaws.com/main/recommendation_unique.webp'),
       ('test3@github.com', 'park', 'https://yansebnb.s3.ap-northeast-2.amazonaws.com/main/recommendation_unique.webp'),
       ('test4@github.com', 'song', 'https://yansebnb.s3.ap-northeast-2.amazonaws.com/main/recommendation_unique.webp'),
       ('test5@github.com', 'jeong', 'https://yansebnb.s3.ap-northeast-2.amazonaws.com/main/recommendation_unique.webp'),
       ('test6@github.com', 'yeon', 'https://yansebnb.s3.ap-northeast-2.amazonaws.com/main/recommendation_unique.webp'),
       ('test7@github.com', 'min', 'https://yansebnb.s3.ap-northeast-2.amazonaws.com/main/recommendation_unique.webp'),
       ('test8@github.com', 'jang', 'https://yansebnb.s3.ap-northeast-2.amazonaws.com/main/recommendation_unique.webp'),
       ('test9@github.com', 'tae', 'https://yansebnb.s3.ap-northeast-2.amazonaws.com/main/recommendation_unique.webp'),
       ('test10@github.com', 'su', 'https://yansebnb.s3.ap-northeast-2.amazonaws.com/main/recommendation_unique.webp'),
       ('test11@github.com', 'ken', 'https://yansebnb.s3.ap-northeast-2.amazonaws.com/main/recommendation_unique.webp'),
       ('test12@github.com', 'sang', 'https://yansebnb.s3.ap-northeast-2.amazonaws.com/main/recommendation_unique.webp'),
       ('test13@github.com', 'yoo', 'https://yansebnb.s3.ap-northeast-2.amazonaws.com/main/recommendation_unique.webp');

insert into room (city, region, district, detail, price, rating, review_count, room_description,
                  bathroom_count, bed_count, check_in_time, check_out_time, max_guest, room_type, room_name,
                  members_id)
values ('서울', '강남구', '테헤란로13길65', '1,2층', 50000, 4.1, 187, '모든 객실은 편안하고 안락함을 선사해 준다. 편안함을 더하기 위해 무선 인터넷(무료), 에어컨, 난방, 선풍기, 유선 인터넷(무료) 등을 제공한다. 본 숙소 투숙 기간 다양한 여가 시설 등을 이용할 수 있다. 아주 좋은 위치에 있고 우수한 시설을 구비한 본 숙소(강남 스테이 힐 게스트하우스)는 서울에서의 잊을 수 없는 추억을 위한 완벽한 장소이다',
        2, 4, 15, 11, 6, 'PENSION', '강남스테이힐', 1),
       ('서울', '마포구', '동교로47길3', '2층', 70000, 4.1, 187, '연남동 중심지의 접근성 좋은 위치에 있다. 홍대역(공항철도)에서 도보 7분 거리이며 지하철, 공항철도, 버스를 이용하기 편리하다. 테마를 가진 여러 카페, 맛집, 연남 센트럴 파크, 테마를 가진 여러 카페, 맛집과도 가깝다.',
        1, 2, 15, 11, 2, 'RESIDENCE', '어디더라', 2),
       ('부산', '수영구', '민수변로', '9', 60000, 4.1, 187, '더웨이브펜션은 광안리 바닷가 앞에 위치한 고급 오션뷰의 65평 펜션이다. 워크샵, MT, 각종 모임 등 단체 행사에 최적화되어 있다.',
        2, 4, 15, 11, 8, 'PENSION', '더웨이브', 3),
       ('서울', '강남구', '논현로105길', '11-17', 30000, 4.1, 187, '여행을 좋아하는 게스트가 여행의 게스트를 위해 디자인한 게스트하우스이다.강남 중심에 위치하고 있어 공항 및 모든 교통편의 접근성이 좋다. 강남로,코엑스,종로,이태원등 서울여행의 핫플레이스와 쉽게 연결이 가능한 대중교통의 중심지에 있다. 여성4인실, 남성4인실, 도미토리이며 관리자가 24시간 함께 생활하는 하우스메이징 서비스를 제공한다. 게스트하우스 G601은 모든 구역 금연구역이다.',
        2, 4, 15, 14, 2, 'RESIDENCE', 'G601', 4),
       ('서울', '강남구', '강남대로62길23', '4층', 70000, 4.1, 187, '마스터즈코스, 코드투게더와 기업 교육 프로그램을 운영합니다.',
        2, 4, 15, 11, 6, 'PENSION', '코드스쿼드', 5),
       ('서울', '송파구', '위성대로2', '1층', 70000, 4.1, 187, '우아한형제들은 대한민국을 넘어 세계를 향해 나아갑니다. 베트남 진출을 시작으로 우아한형제들은 Delivery Hero와 함께 <우아DH아시아>를 설립하고 아시아 사업을 총괄하고 있습니다.',
        2, 4, 15, 11, 6, 'PENSION', '우아한형제들', 6),
       ('서울', '송파구', '송파대로570', '8~26층', 70000, 4.1, 187, '당일배송, 새벽배송, 로켓프레시. 쿠팡은 고객의 삶을 모든 과제의 중심에 두고, 신속함과 편리함, 선택과 가치를 보장하기 위해 매일 부단히 노력하고 있습니다.',
        2, 4, 15, 11, 6, 'PENSION', '쿠팡', 7),
       ('서울', '구로구', '디지털로30길', '28', 70000, 4.1, 187, '중고 거래부터 동네 정보까지, 이웃과 함께해요. 가깝고 따뜻한 당신의 근처를 만들어요.',
        2, 4, 15, 11, 6, 'PENSION', '당근마켓', 8),
       ('성남', '분당구', '정자일로', '95', 110000, 4.1, 187, '네이버는 수많은 SME와 창작자, 파트너들이 미래 기술을 활용해 글로벌 시장에서 더 큰 성장을 이룰 수 있도록 지원하는 글로벌 테크 플랫폼입니다.',
        2, 4, 15, 11, 6, 'PENSION', '네이버', 9),
       ('성남', '분당구', '판교역로', '235', 30000, 4.1, 187, '주식회사 카카오는 대한민국의 IT 기업이다. 국내 1위 모바일 메신저인 카카오톡을 비롯하여, 다음, 카카오 T, 멜론 등 다양한 모바일 서비스를 제공하고 있다',
        2, 4, 15, 11, 6, 'PENSION', '카카오이던가', 10),
       ('성남', '분당구', '판교역로231', '5층', 14000, 4.2, 187, '주식회사 카카오뱅크는 대한민국의 두 번째 인터넷 전문은행이다',
        1, 2, 16, 12, 3, 'RESIDENCE', '카카오뱅크', 11),
       ('성남', '분당구', '황새울로360번길42', '11층', 500000, 4.3, 187, '라인은 네이버 주식회사의 일본 법인이었던 네이버 재팬 이 2011년 6월 23일에 출시한 모바일 메신저이다. 일본에서는 일상생활에 필수인 국민적 서비스로 발전하였다. 한국어 서비스는 2011년 8월 31일부터 시작하였다',
        1, 2, 16, 12, 3, 'RESIDENCE', '라인', 12),
       ('서울', '강남구', '테헤란로131', '13층', 11000, 4.2, 187, '토스뱅크는 대한민국의 인터넷전문은행이다. 토스를 운영하는 비바리퍼블리카가 2019년 인터넷전문은행 진출을 선언하고 2021년 10월 5일부터 영업을 시작했으며 Toss 앱 내에서 실행하는 형태다',
        1, 2, 16, 12, 3, 'RESIDENCE', '토스뱅크', 13),
       ('서울', '강남구', '테헤란로131', '15층', 11000, 4.2, 187, '토스페이먼츠 단 하나로 해결하세요. 전자결제 무료신청 제휴 문의. 월평균 거래액 2.5조 함께하는 가맹점',
        1, 2, 16, 12, 3, 'RESIDENCE', '토스페이먼츠', 14),
       ('성남', '강남구', '역삼로17길 64', '4층', 11000, 4.2, 187, '직방은 대한민국의 부동산 기업이다. 2010년 11월 19일 "채널브리즈"라는 사명으로 최초 설립되었다. 2015년 10월 ''직방''으로 변경되었다. ''직접 찍은 방 사진''을 뜻하며 직방 서비스 자체는 2012년 시작되었다.',
        1, 2, 16, 12, 3, 'RESIDENCE', '직방', 15),
       ('서울', '영등포구', '당산로', '235', 1000, 4.2, 187, '어디회사가 좋을까요',
        1, 2, 16, 12, 3, 'RESIDENCE', '무중력지대', 16);

insert into room_image (url, room_id)
values ('https://yansebnb.s3.ap-northeast-2.amazonaws.com/room/2700978_image2_1.jpeg', 1),
       ('https://yansebnb.s3.ap-northeast-2.amazonaws.com/room/2700980_image2_1.jpeg', 1),
       ('https://yansebnb.s3.ap-northeast-2.amazonaws.com/room/images+(4).jpeg', 1),
       ('https://yansebnb.s3.ap-northeast-2.amazonaws.com/room/2700980_image2_1.jpeg', 2),
       ('https://yansebnb.s3.ap-northeast-2.amazonaws.com/room/2700978_image2_1.jpeg', 2),
       ('https://yansebnb.s3.ap-northeast-2.amazonaws.com/room/house.jpeg', 2),
       ('https://yansebnb.s3.ap-northeast-2.amazonaws.com/room/house.jpeg', 3),
       ('https://yansebnb.s3.ap-northeast-2.amazonaws.com/room/images.jpeg', 3),
       ('https://yansebnb.s3.ap-northeast-2.amazonaws.com/room/images+(4).jpeg', 3),
       ('https://yansebnb.s3.ap-northeast-2.amazonaws.com/room/images+(6).jpeg', 4),
       ('https://yansebnb.s3.ap-northeast-2.amazonaws.com/room/2700978_image2_1.jpeg', 4),
       ('https://yansebnb.s3.ap-northeast-2.amazonaws.com/room/images.jpeg', 4),
       ('https://yansebnb.s3.ap-northeast-2.amazonaws.com/room/4.jpeg', 5),
       ('https://yansebnb.s3.ap-northeast-2.amazonaws.com/room/2700978_image2_1.jpeg', 5),
       ('https://yansebnb.s3.ap-northeast-2.amazonaws.com/room/entire.jpeg', 6),
       ('https://yansebnb.s3.ap-northeast-2.amazonaws.com/room/2700980_image2_1.jpeg', 6),
       ('https://yansebnb.s3.ap-northeast-2.amazonaws.com/room/images+(7).jpeg', 7),
       ('https://yansebnb.s3.ap-northeast-2.amazonaws.com/room/house.jpeg', 7),
       ('https://yansebnb.s3.ap-northeast-2.amazonaws.com/room/images+(6).jpeg', 7),
       ('https://yansebnb.s3.ap-northeast-2.amazonaws.com/room/images+(8).jpeg', 8),
       ('https://yansebnb.s3.ap-northeast-2.amazonaws.com/room/images+(7).jpeg', 8),
       ('https://yansebnb.s3.ap-northeast-2.amazonaws.com/room/images.jpeg', 8),
       ('https://yansebnb.s3.ap-northeast-2.amazonaws.com/room/2700980_image2_1.jpeg', 9),
       ('https://yansebnb.s3.ap-northeast-2.amazonaws.com/room/images+(8).jpeg', 9),
       ('https://yansebnb.s3.ap-northeast-2.amazonaws.com/room/images+(7).jpeg', 9),
       ('https://yansebnb.s3.ap-northeast-2.amazonaws.com/room/images+(1).jpeg', 10),
       ('https://yansebnb.s3.ap-northeast-2.amazonaws.com/room/images+(6).jpeg', 10),
       ('https://yansebnb.s3.ap-northeast-2.amazonaws.com/room/images+(2).jpeg', 11),
       ('https://yansebnb.s3.ap-northeast-2.amazonaws.com/room/GangnamStayHill.jpeg', 11),
       ('https://yansebnb.s3.ap-northeast-2.amazonaws.com/room/images+(3).jpeg', 12),
       ('https://yansebnb.s3.ap-northeast-2.amazonaws.com/room/images+(9).jpeg', 13),
       ('https://yansebnb.s3.ap-northeast-2.amazonaws.com/room/images+(4).jpeg', 14),
       ('https://yansebnb.s3.ap-northeast-2.amazonaws.com/room/GangnamStayHill.jpeg', 14),
       ('https://yansebnb.s3.ap-northeast-2.amazonaws.com/room/images.jpeg', 15),
       ('https://yansebnb.s3.ap-northeast-2.amazonaws.com/room/images+(4).jpeg', 15),
       ('https://yansebnb.s3.ap-northeast-2.amazonaws.com/room/GangnamStayHill.jpeg', 16),
       ('https://yansebnb.s3.ap-northeast-2.amazonaws.com/room/images+(8).jpeg', 16);

insert into reservation (adult_count, child_count, infant_count, check_in_date_time, check_out_date_time,
                         cleaning_fee, discount_policy, room_tax, service_tax, reservation_price,
                         members_id, room_id)
values (2, 1, 0, '2022-05-30', '2022-06-01', 10000.0, 'WEEK', 10.0, 10.0, 20000, 1, 1),
       (2, 1, 0, '2022-05-30', '2022-06-01', 10000.0, 'WEEK', 10.0, 10.0, 20000, 1, 2);

insert into wish (members_id, room_id)
values (1, 1);
